export const REQUEST_COMPANY = 'REQUEST_COMPANY';
export const RESPONSE_COMPANY = 'RESPONSE_COMPANY';
export const FAILURE_RESPONSE_COMPANY = 'FAILURE_RESPONSE_COMPANY';
export const GET_USER_COMPANY = 'GET_USER_COMPANY';


export const REQUEST_REPORTS = 'REQUEST_REPORTS';
export const RESPONSE_REPORTS = 'RESPONSE_REPORTS';
export const FAILURE_RESPONSE_REPORTS = 'FAILURE_RESPONSE_REPORTS';
export const SEND_REPORT_DATE_TO_CALENDAR = 'SEND_REPORT_DATE_TO_CALENDAR';


